### ISSUE TITLE
Running matrix with size > 6 display mistake

### ISSUE THREAD

**Issue by oborys** [liderako/N-puzzle#8]
Traceback (most recent call last):
  File "read.py", line 125, in <module>
    m = convertInMatrix(resultRead)
  File "read.py", line 102, in convertInMatrix
    m = createMatrix(res)
  File "read.py", line 119, in createMatrix
    m.matrix[y][x] = int(n)
ValueError: invalid literal for int() with base 10: ''

**Comment by liderako** [comment]
На linux работает все отлично

**Comment by liderako** [comment]
На маке ошибку не выдает. Вопрос как ошибка возникает????
